CREATE SCHEMA IF NOT EXISTS `Java2SEM` DEFAULT CHARACTER SET utf8 ;

USE `Java2SEM` ;

CREATE TABLE IF NOT EXISTS `periodo` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nomedodia` VARCHAR(100) NOT NULL,
  `tempearaturamaxima` VARCHAR(15) NOT NULL,
  `temperaturaminima` VARCHAR(60) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;